from .citizen import Citizen
from .document import Document
from .user_info import UserInfo
from .district import District
from .house import House
from .mahalla import Mahalla
from .owner import Owner
from .region import Region
from .street import Street
from .family import Family